# config/application.yml
defaults: &defaults
  req_timeout: 9.5
  mail:
    :to = ["gcomesana@cnio.es", "vdelatorre@cnio.es"]
    :password = "Run3ks_3"
    :user = "gcomesana@cnio.es"
    :address = "webmail.cnio.es"
    :port = 587

  tsv:
    tsv_url: "api.openphacts.org" # without the http:// bit and no trailing slash
    target_path : "/target/pharmacology/pages"
    compound_path: "/compound/pharmacology/pages"
    enzyme_path: "/target/enzyme/pharmacology/pages"
    tsv_rails_host: "localhost"
    tsv_rails_port: "3003"
    tsv_rails_path: "/ops_api_calls/protein_info"
    tsv_pharm_rails_path: "/ops_api_calls/pharm_by_protein_name"
    tsv_pharm_page_results: "/tdgui_proxy/get_pharm_by_target_page"


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  req_timeout: 11
